services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
    envVars:
      - key: FLASK_ENV
        value: production
